'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DMSCenter

    Partial Public Class DatenObjekt
        Inherits XPObject
        Dim fID As String
        Public Property ID() As String
            Get
                Return fID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ID), fID, value)
            End Set
        End Property
        Dim fDValue As String
        Public Property DValue() As String
            Get
                Return fDValue
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DValue), fDValue, value)
            End Set
        End Property
        Dim fDActualValue As String
        Public Property DActualValue() As String
            Get
                Return fDActualValue
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DActualValue), fDActualValue, value)
            End Set
        End Property
        Dim fActualDate As DateTime
        Public Property ActualDate() As DateTime
            Get
                Return fActualDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(ActualDate), fActualDate, value)
            End Set
        End Property
        Dim fFK_Domain As Domain
        <Association("DatenObjektReferencesDomain")>
        Public Property FK_Domain() As Domain
            Get
                Return fFK_Domain
            End Get
            Set(ByVal value As Domain)
                SetPropertyValue(Of Domain)(NameOf(FK_Domain), fFK_Domain, value)
            End Set
        End Property
        Dim fPath As String
        Public Property Path() As String
            Get
                Return fPath
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Path), fPath, value)
            End Set
        End Property
        Dim fType As String
        Public Property Type() As String
            Get
                Return fType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Type), fType, value)
            End Set
        End Property
        Dim fDFilter As String
        <Size(SizeAttribute.Unlimited)>
        Public Property DFilter() As String
            Get
                Return fDFilter
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DFilter), fDFilter, value)
            End Set
        End Property
        <Association("FilesnFoldersReferencesDatenObjekt")>
        Public ReadOnly Property FilesnFoldersCollection() As XPCollection(Of FilesnFolders)
            Get
                Return GetCollection(Of FilesnFolders)(NameOf(FilesnFoldersCollection))
            End Get
        End Property
    End Class

End Namespace
