'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DMSCenter

    Partial Public Class DMSUSers
        Inherits XPObject
        Dim fFK_Kunde As Kunde
        <Association("DMSUSersReferencesKunde")>
        Public Property FK_Kunde() As Kunde
            Get
                Return fFK_Kunde
            End Get
            Set(ByVal value As Kunde)
                SetPropertyValue(Of Kunde)(NameOf(FK_Kunde), fFK_Kunde, value)
            End Set
        End Property
        Dim fEmail As String
        Public Property Email() As String
            Get
                Return fEmail
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Email), fEmail, value)
            End Set
        End Property
        Dim fUsername As String
        Public Property Username() As String
            Get
                Return fUsername
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Username), fUsername, value)
            End Set
        End Property
        Dim fStatus As String
        Public Property Status() As String
            Get
                Return fStatus
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Status), fStatus, value)
            End Set
        End Property
    End Class

End Namespace
