'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DMSCenter

    Partial Public Class Domain
        Inherits XPObject
        Dim fName As String
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Name), fName, value)
            End Set
        End Property
        Dim fAktiv1 As Boolean
        Public Property Aktiv1() As Boolean
            Get
                Return fAktiv1
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(Aktiv1), fAktiv1, value)
            End Set
        End Property
        Dim fFK_Kunde As Kunde
        <Association("DomainReferencesKunde")>
        Public Property FK_Kunde() As Kunde
            Get
                Return fFK_Kunde
            End Get
            Set(ByVal value As Kunde)
                SetPropertyValue(Of Kunde)(NameOf(FK_Kunde), fFK_Kunde, value)
            End Set
        End Property
        <Association("DatenObjektReferencesDomain")>
        Public ReadOnly Property DatenObjekts() As XPCollection(Of DatenObjekt)
            Get
                Return GetCollection(Of DatenObjekt)(NameOf(DatenObjekts))
            End Get
        End Property
        <Association("SorbaUsersReferencesDomain")>
        Public ReadOnly Property SorbaUsersCollection() As XPCollection(Of SorbaUsers)
            Get
                Return GetCollection(Of SorbaUsers)(NameOf(SorbaUsersCollection))
            End Get
        End Property
    End Class

End Namespace
