'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DMSCenter

    Partial Public Class Kunde
        Inherits XPObject
        Dim fAdrNr As String
        Public Property AdrNr() As String
            Get
                Return fAdrNr
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(AdrNr), fAdrNr, value)
            End Set
        End Property
        Dim fBezeichnung As String
        Public Property Bezeichnung() As String
            Get
                Return fBezeichnung
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Bezeichnung), fBezeichnung, value)
            End Set
        End Property
        Dim fDMSAdresse As String
        Public Property DMSAdresse() As String
            Get
                Return fDMSAdresse
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DMSAdresse), fDMSAdresse, value)
            End Set
        End Property
        Dim fDMSUser As String
        Public Property DMSUser() As String
            Get
                Return fDMSUser
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DMSUser), fDMSUser, value)
            End Set
        End Property
        Dim fDMSPassword As String
        Public Property DMSPassword() As String
            Get
                Return fDMSPassword
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DMSPassword), fDMSPassword, value)
            End Set
        End Property
        Dim fSorbaWebservice As String
        Public Property SorbaWebservice() As String
            Get
                Return fSorbaWebservice
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SorbaWebservice), fSorbaWebservice, value)
            End Set
        End Property
        Dim fSorbaUser As String
        Public Property SorbaUser() As String
            Get
                Return fSorbaUser
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SorbaUser), fSorbaUser, value)
            End Set
        End Property
        Dim fSorbaPassword As String
        Public Property SorbaPassword() As String
            Get
                Return fSorbaPassword
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SorbaPassword), fSorbaPassword, value)
            End Set
        End Property
        Dim fDMSUserTeamfolder As String
        Public Property DMSUserTeamfolder() As String
            Get
                Return fDMSUserTeamfolder
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DMSUserTeamfolder), fDMSUserTeamfolder, value)
            End Set
        End Property
        Dim fDMSPasswortTeamfolder As String
        Public Property DMSPasswortTeamfolder() As String
            Get
                Return fDMSPasswortTeamfolder
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DMSPasswortTeamfolder), fDMSPasswortTeamfolder, value)
            End Set
        End Property
        <Association("DomainReferencesKunde")>
        Public ReadOnly Property Domains() As XPCollection(Of Domain)
            Get
                Return GetCollection(Of Domain)(NameOf(Domains))
            End Get
        End Property
        <Association("MySorbaUsersReferencesKunde")>
        Public ReadOnly Property MySorbaUsersCollection() As XPCollection(Of MySorbaUsers)
            Get
                Return GetCollection(Of MySorbaUsers)(NameOf(MySorbaUsersCollection))
            End Get
        End Property
        <Association("DMSUSersReferencesKunde")>
        Public ReadOnly Property DMSUSersCollection() As XPCollection(Of DMSUSers)
            Get
                Return GetCollection(Of DMSUSers)(NameOf(DMSUSersCollection))
            End Get
        End Property
    End Class

End Namespace
