'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DMSCenter

    Partial Public Class MySorbaUsers
        Inherits XPObject
        Dim fFK_Kunde As Kunde
        <Association("MySorbaUsersReferencesKunde")>
        Public Property FK_Kunde() As Kunde
            Get
                Return fFK_Kunde
            End Get
            Set(ByVal value As Kunde)
                SetPropertyValue(Of Kunde)(NameOf(FK_Kunde), fFK_Kunde, value)
            End Set
        End Property
        Dim fMySorbaUsername As String
        Public Property MySorbaUsername() As String
            Get
                Return fMySorbaUsername
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(MySorbaUsername), fMySorbaUsername, value)
            End Set
        End Property
        Dim fAktiv As Boolean
        Public Property Aktiv() As Boolean
            Get
                Return fAktiv
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(Aktiv), fAktiv, value)
            End Set
        End Property
        Dim fDMSUsername As String
        Public Property DMSUsername() As String
            Get
                Return fDMSUsername
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DMSUsername), fDMSUsername, value)
            End Set
        End Property
    End Class

End Namespace
