'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace DMSCenter

    Partial Public Class SorbaUsers
        Inherits XPObject
        Dim fFK_Domain As Domain
        <Association("SorbaUsersReferencesDomain")>
        Public Property FK_Domain() As Domain
            Get
                Return fFK_Domain
            End Get
            Set(ByVal value As Domain)
                SetPropertyValue(Of Domain)(NameOf(FK_Domain), fFK_Domain, value)
            End Set
        End Property
        Dim fUSERNAME As String
        Public Property USERNAME() As String
            Get
                Return fUSERNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USERNAME), fUSERNAME, value)
            End Set
        End Property
        Dim fSUCH_NAME As String
        Public Property SUCH_NAME() As String
            Get
                Return fSUCH_NAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SUCH_NAME), fSUCH_NAME, value)
            End Set
        End Property
        Dim fMYSUSER As String
        Public Property MYSUSER() As String
            Get
                Return fMYSUSER
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(MYSUSER), fMYSUSER, value)
            End Set
        End Property
        Dim fUSERGROUP As String
        Public Property USERGROUP() As String
            Get
                Return fUSERGROUP
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USERGROUP), fUSERGROUP, value)
            End Set
        End Property
        Dim fGROUP As Boolean
        Public Property GROUP() As Boolean
            Get
                Return fGROUP
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(GROUP), fGROUP, value)
            End Set
        End Property
        Dim fGR_ROLE As Boolean
        Public Property GR_ROLE() As Boolean
            Get
                Return fGR_ROLE
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(GR_ROLE), fGR_ROLE, value)
            End Set
        End Property
        Dim fM_MQ As Boolean
        Public Property M_MQ() As Boolean
            Get
                Return fM_MQ
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(M_MQ), fM_MQ, value)
            End Set
        End Property
        Dim fPERSONAL As String
        Public Property PERSONAL() As String
            Get
                Return fPERSONAL
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(PERSONAL), fPERSONAL, value)
            End Set
        End Property
        Dim fMY_PRJ As Boolean
        Public Property MY_PRJ() As Boolean
            Get
                Return fMY_PRJ
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(MY_PRJ), fMY_PRJ, value)
            End Set
        End Property
        Dim fPRJOWNER As Boolean
        Public Property PRJOWNER() As Boolean
            Get
                Return fPRJOWNER
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(PRJOWNER), fPRJOWNER, value)
            End Set
        End Property
        Dim fM_PROJ As Boolean
        Public Property M_PROJ() As Boolean
            Get
                Return fM_PROJ
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(M_PROJ), fM_PROJ, value)
            End Set
        End Property
        Dim fM_AQ As Boolean
        Public Property M_AQ() As Boolean
            Get
                Return fM_AQ
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(M_AQ), fM_AQ, value)
            End Set
        End Property
        Dim fM_FIBU As Boolean
        Public Property M_FIBU() As Boolean
            Get
                Return fM_FIBU
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(M_FIBU), fM_FIBU, value)
            End Set
        End Property
        Dim fPRJ_ACCESS As Boolean
        Public Property PRJ_ACCESS() As Boolean
            Get
                Return fPRJ_ACCESS
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)(NameOf(PRJ_ACCESS), fPRJ_ACCESS, value)
            End Set
        End Property
    End Class

End Namespace
